// Automatically generated by litmus

void test_body(int pid)
{
  switch (pid) {
    case 0: {
      var_t out0;
      arch_barrier_up();
      delay(test.delays[0]*12);

      *test.vars[0] = 1;
      out0 = *test.vars[1];

      test.outcome[0] = out0;
      arch_barrier_down();
      break;
    }
    case 1: {
      var_t out0;
      arch_barrier_up();
      delay(test.delays[1]*12);

      *test.vars[1] = 1;
      out0 = *test.vars[0];

      test.outcome[1] = out0;
      arch_barrier_down();
      break;
    }
  }
}
