// Automatically generated by litmus

#ifndef _TESTCASE_H_
#define _TESTCASE_H_

#define NUM_PROCESSES    2
#define NUM_ITERATIONS   1000
#define NUM_VARS         2
#define NUM_LOCS         64
#define LOC_GRAIN        1
#define LEN_OUTCOME      2
#define OUTCOME_NAMES    { "0:a3", "1:a3" }
#define OUTCOME_SOUGHT   { 0, 0 }

#endif
